export const K8S_URL_PREFIX = '/kubernetes/api/v1.10/'
export const KF_URL_PREFIX = '/kingfisher/api/v1.10/'
export const ISTIO_URL_PREFIX = '/istio/api/v1.10/'
export const INSPECT_URL_PREFIX = '/inspect/api/v1.10/'
export const RUNNER_URL_PREFIX = '/runner/api/v1.10/'
